server:
  port: 9080

scheduler:
  redisSyncJobInterval: 30000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: mongoadmin
      password: admin
      authentication-database: mongodb
#quartz
  quartz:
    job-store-type: memory
    scheduler-name: QuartzSchedulerRedis

#redis
  redis:
    host: localhost
    port: 6379