server:
  port: 9080
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb
      username: mongoadmin
      password: admin
      authentication-database: mongodb